version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      - run: nvm install --lts 
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Install Testing Dependencies
          command: cd test/e2e ; ls ; npm install
      - run:
          name: Download Sauce Connect Proxy
          command: wget https://saucelabs.com/downloads/sc-4.7.1-linux.tar.gz
      - run:
          name: Extract tar file for linux
          command: tar -xf sc-4.7.1-linux.tar.gz
      - run:
          name: Start Sauce Labs Tunnel
          background: true
          command: ./sc-4.7.1-linux/bin/sc -u sso-optum-hyusein.hyuseinov -k 8c08d53c-97b0-4dc2-8edf-cc2d46c1784c --region us-west --tunnel-name sso-optum-hyusein.hyuseinov_tunnel_name
      - run:
          name: Wait for port
          command: |
            while ! nc -z localhost 4445; do
              sleep 1
            done
      - run: |
          cd test/e2e
          npm run sauce
      #- run:
      #    name: Start Sauce Labs Tunnel
      #    command: ./sc-4.7.1-linux/bin/sc -u sso-optum-hyusein.hyuseinov -k 8c08d53c-97b0-4dc2-8edf-cc2d46c1784c --region us-west --tunnel-name sso-optum-hyusein.hyuseinov_tunnel_name &
      #- run:
      #    name: Run Sauce Labs Tests
      #    command: cd test/e2e ; sleep 60 ; npm run sauce
