
version: 2.1
orbs: 
  allure: ayte/allure@0.1.3
dependencies:
  cache_directories:
    - "test/e2e/node_modules"
workflows:
  test-deploy:
    jobs:
      - build
      - test


jobs:  
  build:
    macos:
      xcode: 13.0.0
    steps:
      - run: open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/
      - run: brew install watchman
      - checkout
      - run: ls
      - run: node --version
      - run: yarn install
      - run: cd ios ; pod install
      - run: yarn react-native run-ios
  test:
    machine:
      image: ubuntu-2004:202104-01
    steps: 
      - checkout
      - allure/install
      - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      - run: nvm install --lts 
    #  - run:
    #      name: Install Dependencies
    #      command: yarn install
      - run:
          name: Install Testing Dependencies
          command: cd test/e2e ; ls ; npm install
     # - run:
     #     name: Install Allure-Reporter
     #     command: cd test/e2e ; npm i allure-commandline
       
      - run:
          name: Download Sauce Connect Proxy
          command: wget https://saucelabs.com/downloads/sc-4.7.1-linux.tar.gz
      - run:
          name: Extract tar file for linux
          command: tar -xf sc-4.7.1-linux.tar.gz
      - run:
         background: true
         command: ./sc-4.7.1-linux/bin/sc --user sso-optum-hyusein.hyuseinov --api-key 8c08d53c-97b0-4dc2-8edf-cc2d46c1784c --readyfile ~/sauce_is_ready
       
  
      - run: |
          while [ ! -e ~/sauce_is_ready ]; do sleep 1; done
          cd test/e2e
          npm run sauce

      - run:
          name: Generate Allure Report
          command: cd test/e2e; allure generate allure-results

      - store_artifacts:
          path: test/e2e/allure-report
