version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout
      - run: node --version
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Install Testing Dependencies
          command: cd test/e2e ; ls ; npm install
      - run:
          name: Download Sauce Connect Proxy
          command: wget https://saucelabs.com/downloads/sc-4.7.1-linux.tar.gz
      - run:
          name: Extract tar file for linux
          command: tar -xf sc-4.7.1-linux.tar.gz
      - run:
          name: Start Sauce Labs Tunnel
          command: ./sc-4.7.1-linux/bin/sc -u sso-optum-hyusein.hyuseinov -k 8c08d53c-97b0-4dc2-8edf-cc2d46c1784c -x https://api.us-west-1.saucelabs.com/rest/v1 -i sso-optum-hyusein.hyuseinov_tunnel_id &
      - run:
          name: Run Sauce Labs Tests
          command: cd test/e2e ; sleep 30 ; npm run sauce
